# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print (np.version.version)

1.20.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.12398753 0.00675229 0.94077661 0.53663567 0.96615587]
  [0.3594862  0.86689429 0.8247102  0.05523766 0.31873767]
  [0.81000865 0.37099742 0.67818087 0.99512194 0.02598718]]

 [[0.76481384 0.38826723 0.86609485 0.5357248  0.28930693]
  [0.9614996  0.16673752 0.07233747 0.90396431 0.57013355]
  [0.36689424 0.17275972 0.84881352 0.42189374 0.42013104]]]


In [5]:
# Method 2
a = np.random.randint(0,100,(2,3,5))
print(a)

[[[14 62 18 14 57]
  [ 1 75 70 87 32]
  [34 55 94 95 23]]

 [[92 82 22 31  0]
  [56 97 96 47 68]
  [39 67 19 11 57]]]


In [15]:
# Method 3
a = np.random.randn(2,3,5)
print(a)

[[[-0.24871494  1.04620799 -0.08223207 -0.93367388  1.7074926 ]
  [ 1.80768543 -0.52855333 -1.24730164  1.18305522 -0.86826338]
  [-0.21597101 -0.51052825  0.60534531 -0.50157887  1.3305003 ]]

 [[-2.1693289   1.68518174 -0.0044509  -0.2273126   1.71740729]
  [ 0.47955267  0.94690226  1.74769745 -0.67524247  1.1401866 ]
  [-1.14089256 -0.98943147  0.66057259  1.68687025 -1.47884507]]]


#### 4. Print *a*.


In [16]:
# your code here
print(a)

[[[-0.24871494  1.04620799 -0.08223207 -0.93367388  1.7074926 ]
  [ 1.80768543 -0.52855333 -1.24730164  1.18305522 -0.86826338]
  [-0.21597101 -0.51052825  0.60534531 -0.50157887  1.3305003 ]]

 [[-2.1693289   1.68518174 -0.0044509  -0.2273126   1.71740729]
  [ 0.47955267  0.94690226  1.74769745 -0.67524247  1.1401866 ]
  [-1.14089256 -0.98943147  0.66057259  1.68687025 -1.47884507]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [17]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [18]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [19]:
# your code here
if a.size == b.size:
    print ("True")


True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [20]:
# your answer here
#No, cause they have different shapes and it wouldnt make any mathematical sense to sum them up.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [21]:
# your code here
b = np.reshape(b, (2,3,5))

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [22]:
# your code/answer here
d = (np.add(a,b))
print(d)

[[[ 0.75128506  2.04620799  0.91776793  0.06632612  2.7074926 ]
  [ 2.80768543  0.47144667 -0.24730164  2.18305522  0.13173662]
  [ 0.78402899  0.48947175  1.60534531  0.49842113  2.3305003 ]]

 [[-1.1693289   2.68518174  0.9955491   0.7726874   2.71740729]
  [ 1.47955267  1.94690226  2.74769745  0.32475753  2.1401866 ]
  [-0.14089256  0.01056853  1.66057259  2.68687025 -0.47884507]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [23]:
# your code/answer here
print(a,b)
#explain what

[[[-0.24871494  1.04620799 -0.08223207 -0.93367388  1.7074926 ]
  [ 1.80768543 -0.52855333 -1.24730164  1.18305522 -0.86826338]
  [-0.21597101 -0.51052825  0.60534531 -0.50157887  1.3305003 ]]

 [[-2.1693289   1.68518174 -0.0044509  -0.2273126   1.71740729]
  [ 0.47955267  0.94690226  1.74769745 -0.67524247  1.1401866 ]
  [-1.14089256 -0.98943147  0.66057259  1.68687025 -1.47884507]]] [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [24]:
# your code here
e = np.multiply(a,b)
print(e)

[[[-0.24871494  1.04620799 -0.08223207 -0.93367388  1.7074926 ]
  [ 1.80768543 -0.52855333 -1.24730164  1.18305522 -0.86826338]
  [-0.21597101 -0.51052825  0.60534531 -0.50157887  1.3305003 ]]

 [[-2.1693289   1.68518174 -0.0044509  -0.2273126   1.71740729]
  [ 0.47955267  0.94690226  1.74769745 -0.67524247  1.1401866 ]
  [-1.14089256 -0.98943147  0.66057259  1.68687025 -1.47884507]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [25]:
# your code/answer here
#I just multiplied them by one

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [26]:
# your code here
d_mean = np.mean(d)
d_min = np.min(d)
d_max = np.max(d)
print(d_mean, d_max, d_min)

1.1974112123141905 2.8076854253687755 -1.1693288953921095


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [27]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [49]:
# your code here
lst = []
for i in np.nditer(d):
            if i > d_min and i < d_mean:
                lst.append(25)
            elif i > d_mean and i < d_max:
                lst.append(75)
            elif i == d_mean:
                lst.append(50)
            elif i == d_min:
                lst.append(0)
            elif i == d_max:
                lst.append(100)  

lst = np.reshape(lst, (2,3,5))
print(lst)

[[[ 25  75  25  25  75]
  [100  25  25  75  25]
  [ 25  25  75  25  75]]

 [[  0  75  25  25  75]
  [ 75  75  75  25  75]
  [ 25  25  75  75  25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [50]:
lst = []
for i in np.nditer(d):
            if i > d_min and i < d_mean:
                lst.append("B")
            elif i > d_mean and i < d_max:
                lst.append("D")
            elif i == d_mean:
                lst.append("C")
            elif i == d_min:
                lst.append("A")
            elif i == d_max:
                lst.append("E")  

lst = np.reshape(lst, (2,3,5))
print(lst)

[[['B' 'D' 'B' 'B' 'D']
  ['E' 'B' 'B' 'D' 'B']
  ['B' 'B' 'D' 'B' 'D']]

 [['A' 'D' 'B' 'B' 'D']
  ['D' 'D' 'D' 'B' 'D']
  ['B' 'B' 'D' 'D' 'B']]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here